PROGRAM = nvimtoggle
LOCATION = /usr/bin/nvimtoggle
BASHFILE = ./toggle/nvimtoggle.bash

default: $(BASHFILE)
  chmod +x $(BASHFILE)
  cp $(BASHFILE) $(LOCATION)
  echo 'Installed as $(PROGRAM)'
  echo 'in $(LOCATION)'

install: default

all: default

.PHONY: clean

clean:
  rm -f $(LOCATION)
